### Site Settings ###
title               : dev.dongwon
description         : >-
                      Enjoy the imperfections
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : dev-dongwon/dev-dongwon.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : YoussefRaafatNasry/portfolYOU


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name              : Dongwon Kim
  image             : https://media.vlpt.us/images/dev-tuna/profile/70765305-5125-4ab4-8f8a-bc776673b3ce/T74H5245A-UHGPGDXAQ-90b52bcb4e49-512.jpg
# behance           : your_username
# dribbble          : your_username
  email             : dev.dongwonkim@gmail.com
# facebook          : your_username
  github            : dev-dongwon
# gitlab            : your_username
# instagram         : your_username
# kaggle            : your_username
  linkedin          : dongwonKim
# medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
# twitter           : your_username
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name

### Disqus ###
disqus:
  shortname: dev-dongwon                     # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: true                                        # Set true to enable analytics
  google:
    tracking_id: UA-147263127-1


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: true                                   # Set to true to enable disqus comments

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
