### Site Settings ###
title               : 개발항해일지
description         : >-
                      start line
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : dev-dongwon/dev-dongwon.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : YoussefRaafatNasry/portfolYOU


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - documentation/partials/**                           # For Documentation Only


### Author Info ###
author:
  name              : Dongwon Kim
  image             : https://media-exp1.licdn.com/dms/image/C5603AQE0Hcxk8y3guw/profile-displayphoto-shrink_200_200/0/1611328103862?e=1617235200&v=beta&t=N-y622oljFzg8UROt8UoP_pCcV4GKnHnq6vGCSTUoUo
# behance           : your_username
# dribbble          : your_username
  email             : dev.dongwonkim@gmail.com
# facebook          : your_username
  github            : dev-dongwon
# gitlab            : your_username
# instagram         : your_username
# kaggle            : your_username
  linkedin          : 동원-김-675b43198
# medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
# twitter           : your_username
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  elements:                                             # For Documentation Only
    output: true                                        # For Documentation Only


### Disqus ###
disqus:
  shortname: dev-dongwon                   # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: true                                        # Set true to enable analytics
  google:
    tracking_id: UA-147263127-1


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: true                                   # Set to true to enable disqus comments

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
